### ISSUE TITLE
Add legend for colours on report

### ISSUE THREAD

**Issue by hshuaib90** [GSTT-CSC/TotalSegmentator-AIDE#34]
Feedback from KCH: Can we add a legend for the colours on the AIDE Clinical Review PDF report 
![image](https://github.com/GSTT-CSC/TotalSegmentator-AIDE/assets/19840489/4927ac54-4a98-4af5-abd6-aae9aff658e3)

**Comment by AnilMistry** [comment]
Happy to add the index for the sake of the report, but the colours represented in the diagram are not the same colours that will appear in the radiotherapy Treatment Planning system; these are assigned colours when uploaded. 

They can technically be assigned as colours in the dicom metadata (3006,002A) : ( 0-255 RGB value)...

 https://dicom.innolitics.com/ciods/rt-structure-set/roi-contour/30060039/3006002 

However this should match local practice, some departments can be fairly regimented about certain contours colours.

**Comment by hshuaib90** [comment]
Ok in that case happy to leave it be.
