### ISSUE TITLE
Problem when installing pycairo from requirements.txt

### ISSUE THREAD

**Issue by MLK97** [GSTT-CSC/TotalSegmentator-AIDE#40]
Hey,

first of all a wonderful package and documentation you are distributing here.

I tried to install the TotalSegmentator-AIDE package with the walkthrough you described in your README.md.
When running `pip3 install -r requirements.txt` I got an error when installing `pycairo`.
I was eventually able to fix this by running `sudo apt install libcairo2-dev`.
Perhaps it would be a nice addition to the manual to give this as a troubleshooting solution in case others also encounter the issue.

**Comment by tomaroberts** [comment]
Thanks for raising the issue! Added to README.
